spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.3.121:3306/orange?useSSL=false&serverTimezone=UTC
    username: root
  redis:
    host: 192.168.3.201
    password: redis-01
  rabbitmq:
    host: 192.168.3.201
    username: test
    password: test
    virtual-host: /
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: yt.cart.exchange
    publisher-confirms: true
  application:
    name: order-service
dubbo:
  application:
    name: yitao-order-service
    qos-enable: false
  protocol:
    port: 20888
  registry:
    address: zookeeper://192.168.3.201:2181
#    address: zookeeper://192.168.3.220:2181?backup=192.168.3.221:2181,192.168.3.222:2181
logging:
  level:
    com.gerry.yitao.mapper: debug
server:
  port: 9999
# 调用外部服务接口的前缀
client:
  url: http://api.yitao.com/
yt:
  worker:
    workerId: 29
    dataCenterId: 12
  wxpay:
    appID: wxfbe945846a930d33
    mchID: 1516374691
    key: 5d9f0cc242b22326934f0b7857c9a040
    certPath: D:/vip/keys/apiclient_cert.p12
    notifyUrl: http://i38psr.natappfree.cc/wxpay/notify