

logging:
  level:
    # feign日志以什么级别监控哪个接口
    org:
      springframework:
        cloud: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 015310qq
    url: rog.pub

