//常量
var WCMConstants = {
	DEBUG : false,
	WCM_VERSION : 'WCM v6.1',
	WCM_BUILDNO : 'b10001',
	WCM_APPNAME : 'wcm',
	WCM_ROOTPATH : '/wcm/',
	WCM6_PATH : '/wcm/app/',
	WCM_LOCAL_URL : '/wcm/app/localxml/',
	WCM_ROMOTE_URL : '/wcm/center.do',
	WCM_NOT_LOGIN_PAGE : '/wcm/console/include/not_login.htm',
	OPER_TYPE_SEP : 'seperate',
	WCM_EVENT_FLAG : 'wcm.CMSObjEvent',
	TAB_HOST_TYPE_CHANNEL : 'channel',
	TAB_HOST_TYPE_WEBSITE : 'website',
	TAB_HOST_TYPE_WEBSITEROOT : 'websiteroot',
	TAB_HOST_TYPE_MYFLOWDOCLIST : 'myFlowDocList',
	TAB_HOST_TYPE_MYMSGLIST : 'myMsgList',
	TAB_HOST_TYPE_TRSSERVERLIST : 'trsServerList',
	TAB_HOST_TYPE_METAVIEW : 'metaview',
	TAB_HOST_TYPE_CLASSINFO : 'classinfo',
	OBJ_TYPE_DOCUMENT : 'document',
	OBJ_TYPE_CHNLDOC : 'chnldoc',
	OBJ_TYPE_WEBSITE : 'website',
	OBJ_TYPE_WEBSITEROOT : 'websiteroot',
	OBJ_TYPE_CHANNEL : 'channel',
	OBJ_TYPE_CHANNELMASTER : 'channelMaster',
	OBJ_TYPE_TREENODE : 'TreeNode',
	OBJ_TYPE_CLSTREENODE : 'ClsTreeNode',
	OBJ_TYPE_GRIDROW : 'GridRow',
	OBJ_TYPE_CELL : 'GridCell',
	OBJ_TYPE_UNKNOWN : 'UnKnown',
	OBJ_TYPE_MYFLOWDOCLIST : 'myFlowDocList',
	OBJ_TYPE_TRSSERVERLIST : 'trsServerList',
	OBJ_TYPE_TRSSERVER : 'trsServer',
	OBJ_TYPE_MYMSGLIST : 'myMsgList',
	OBJ_TYPE_METAVIEW : 'metaview',
	OBJ_TYPE_CLASSINFO : 'classinfo',
	OBJ_TYPE_MAINPAGE : 'MainPage',
	OBJ_TYPE_SYSTEM : 'System',
	OBJ_TYPE_SEARCH : 'Search',
	OBJ_TYPE_ALL : 'All',
	OBJ_TYPE_ALL_CMSOBJS : 'All_CMSObjs',
	OBJ_TYPE_DOCUMENTBAK : 'documentbak',
	OBJ_TYPE_SITERECYCLE : 'SiteRecycle',
	OBJ_TYPE_CHNLRECYCLE : 'Chnlrecycle',
	OBJ_TYPE_INFOVIEWDOC :  'infoviewdoc',
	OBJ_TYPE_REGION : 'region'
};
Ext.ns('WCMLANG', 'wcm.LANG');
WCMLANG = wcm.LANG;