server:
  port: 10080
dubbo:
  application:
    name: yitao-order-web
    qos-enable: false
  registry:
    address: zookeeper://192.168.3.201:2181
#    address: zookeeper://192.168.3.220:2181?backup=192.168.3.221:2181,192.168.3.222:2181
spring:
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: common