package com.gwssi.report.shenziqiye;

import java.util.List;
import java.util.Map;

public class ShuLiangUtil {
	public String shuLiangUtils(List<Map> num) {
		StringBuffer sb = new StringBuffer();
		sb.append("<html xmlns:o=\"urn:schemas-microsoft-com:office:office\"\n"
				+ "xmlns:x=\"urn:schemas-microsoft-com:office:excel\"\n"
				+ "xmlns=\"http://www.w3.org/TR/REC-html40\">\n"
				+ "\n"
				+ "<head>\n"
				+ "<meta http-equiv=Content-Type content=\"text/html; charset=utf-8\">\n"
				+ "<meta name=ProgId content=Excel.Sheet>\n"
				+ "<meta name=Generator content=\"Microsoft Excel 15\">\n"
				+ "<link rel=File-List href=\"表4%20前海片区总量企业行业分布.files/filelist.xml\">\n"
				+ "<style id=\"深资背景企业数量_15089_Styles\">\n"
				+ "<!--table\n"
				+ "  {mso-displayed-decimal-separator:\"\\.\";\n"
				+ "  mso-displayed-thousand-separator:\"\\,\";}\n"
				+ ".font515089\n"
				+ "  {color:windowtext;\n"
				+ "  font-size:9.0pt;\n"
				+ "  font-weight:400;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:宋体;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;}\n"
				+ ".font615089\n"
				+ "  {color:windowtext;\n"
				+ "  font-size:9.0pt;\n"
				+ "  font-weight:400;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:等线;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;}\n"
				+ ".xl1515089\n"
				+ "  {padding-top:1px;\n"
				+ "  padding-right:1px;\n"
				+ "  padding-left:1px;\n"
				+ "  mso-ignore:padding;\n"
				+ "  color:black;\n"
				+ "  font-size:11.0pt;\n"
				+ "  font-weight:400;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:等线;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-number-format:General;\n"
				+ "  text-align:general;\n"
				+ "  vertical-align:bottom;\n"
				+ "  mso-background-source:auto;\n"
				+ "  mso-pattern:auto;\n"
				+ "  white-space:nowrap;}\n"
				+ ".xl6415089\n"
				+ "  {padding-top:1px;\n"
				+ "  padding-right:1px;\n"
				+ "  padding-left:1px;\n"
				+ "  mso-ignore:padding;\n"
				+ "  color:black;\n"
				+ "  font-size:11.0pt;\n"
				+ "  font-weight:400;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:等线;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-number-format:General;\n"
				+ "  text-align:center;\n"
				+ "  vertical-align:middle;\n"
				+ "  border:.5pt solid windowtext;\n"
				+ "  mso-background-source:auto;\n"
				+ "  mso-pattern:auto;\n"
				+ "  white-space:nowrap;}\n"
				+ ".xl6515089\n"
				+ "  {padding-top:1px;\n"
				+ "  padding-right:1px;\n"
				+ "  padding-left:1px;\n"
				+ "  mso-ignore:padding;\n"
				+ "  color:black;\n"
				+ "  font-size:11.0pt;\n"
				+ "  font-weight:400;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:等线;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-number-format:General;\n"
				+ "  text-align:center;\n"
				+ "  vertical-align:middle;\n"
				+ "  border:.5pt solid windowtext;\n"
				+ "  mso-background-source:auto;\n"
				+ "  mso-pattern:auto;\n"
				+ "  white-space:nowrap;}\n"
				+ ".xl6615089\n"
				+ "  {padding-top:1px;\n"
				+ "  padding-right:1px;\n"
				+ "  padding-left:1px;\n"
				+ "  mso-ignore:padding;\n"
				+ "  color:black;\n"
				+ "  font-size:10.0pt;\n"
				+ "  font-weight:400;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:微软雅黑, sans-serif;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-number-format:General;\n"
				+ "  text-align:center;\n"
				+ "  vertical-align:middle;\n"
				+ "  border:.5pt solid windowtext;\n"
				+ "  mso-background-source:auto;\n"
				+ "  mso-pattern:auto;\n"
				+ "  white-space:nowrap;}\n"
				+ ".xl6715089\n"
				+ "  {padding-top:1px;\n"
				+ "  padding-right:1px;\n"
				+ "  padding-left:1px;\n"
				+ "  mso-ignore:padding;\n"
				+ "  color:black;\n"
				+ "  font-size:11.0pt;\n"
				+ "  font-weight:400;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:等线;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-number-format:Percent;\n"
				+ "  text-align:general;\n"
				+ "  vertical-align:middle;\n"
				+ "  border:.5pt solid windowtext;\n"
				+ "  mso-background-source:auto;\n"
				+ "  mso-pattern:auto;\n"
				+ "  white-space:nowrap;}\n"
				+ ".xl6815089\n"
				+ "  {padding-top:1px;\n"
				+ "  padding-right:1px;\n"
				+ "  padding-left:1px;\n"
				+ "  mso-ignore:padding;\n"
				+ "  color:black;\n"
				+ "  font-size:11.0pt;\n"
				+ "  font-weight:400;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:等线;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-number-format:Percent;\n"
				+ "  text-align:general;\n"
				+ "  vertical-align:middle;\n"
				+ "  border:.5pt solid windowtext;\n"
				+ "  mso-background-source:auto;\n"
				+ "  mso-pattern:auto;\n"
				+ "  white-space:nowrap;}\n"
				+ ".xl6915089\n"
				+ "  {padding-top:1px;\n"
				+ "  padding-right:1px;\n"
				+ "  padding-left:1px;\n"
				+ "  mso-ignore:padding;\n"
				+ "  color:black;\n"
				+ "  font-size:10.0pt;\n"
				+ "  font-weight:400;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:微软雅黑, sans-serif;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-number-format:General;\n"
				+ "  text-align:center;\n"
				+ "  vertical-align:middle;\n"
				+ "  border:.5pt solid windowtext;\n"
				+ "  mso-background-source:auto;\n"
				+ "  mso-pattern:auto;\n"
				+ "  white-space:normal;}\n"
				+ ".xl7015089\n"
				+ "  {padding-top:1px;\n"
				+ "  padding-right:1px;\n"
				+ "  padding-left:1px;\n"
				+ "  mso-ignore:padding;\n"
				+ "  color:black;\n"
				+ "  font-size:12.0pt;\n"
				+ "  font-weight:700;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:等线;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-number-format:General;\n"
				+ "  text-align:center;\n"
				+ "  vertical-align:middle;\n"
				+ "  border-top:.5pt solid windowtext;\n"
				+ "  border-right:none;\n"
				+ "  border-bottom:.5pt solid windowtext;\n"
				+ "  border-left:.5pt solid windowtext;\n"
				+ "  mso-background-source:auto;\n"
				+ "  mso-pattern:auto;\n"
				+ "  white-space:nowrap;}\n"
				+ ".xl7115089\n"
				+ "  {padding-top:1px;\n"
				+ "  padding-right:1px;\n"
				+ "  padding-left:1px;\n"
				+ "  mso-ignore:padding;\n"
				+ "  color:black;\n"
				+ "  font-size:12.0pt;\n"
				+ "  font-weight:700;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:等线;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-number-format:General;\n"
				+ "  text-align:center;\n"
				+ "  vertical-align:middle;\n"
				+ "  border-top:.5pt solid windowtext;\n"
				+ "  border-right:none;\n"
				+ "  border-bottom:.5pt solid windowtext;\n"
				+ "  border-left:none;\n"
				+ "  mso-background-source:auto;\n"
				+ "  mso-pattern:auto;\n"
				+ "  white-space:nowrap;}\n"
				+ ".xl7215089\n"
				+ "  {padding-top:1px;\n"
				+ "  padding-right:1px;\n"
				+ "  padding-left:1px;\n"
				+ "  mso-ignore:padding;\n"
				+ "  color:black;\n"
				+ "  font-size:12.0pt;\n"
				+ "  font-weight:700;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:等线;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-number-format:General;\n"
				+ "  text-align:center;\n"
				+ "  vertical-align:middle;\n"
				+ "  border-top:.5pt solid windowtext;\n"
				+ "  border-right:.5pt solid windowtext;\n"
				+ "  border-bottom:.5pt solid windowtext;\n"
				+ "  border-left:none;\n"
				+ "  mso-background-source:auto;\n"
				+ "  mso-pattern:auto;\n"
				+ "  white-space:nowrap;}\n"
				+ "ruby\n"
				+ "  {ruby-align:left;}\n"
				+ "rt\n"
				+ "  {color:windowtext;\n"
				+ "  font-size:9.0pt;\n"
				+ "  font-weight:400;\n"
				+ "  font-style:normal;\n"
				+ "  text-decoration:none;\n"
				+ "  font-family:等线;\n"
				+ "  mso-generic-font-family:auto;\n"
				+ "  mso-font-charset:134;\n"
				+ "  mso-char-type:none;}\n"
				+ "-->\n"
				+ "</style>\n"
				+ "</head>\n"
				+ "\n"
				+ "<body>\n"
				+ "\n"
				+ "\n"
				+ "<div id=\"深资背景企业数量_15089\" align=center x:publishsource=\"Excel\">\n"
				+ "\n"
				+ "<table border=0 cellpadding=0 cellspacing=0 width=400 style='border-collapse:\n"
				+ " collapse;table-layout:fixed;width:300pt'>\n"
				+ " <col width=223 style='mso-width-source:userset;mso-width-alt:7136;width:167pt'>\n"
				+ " <col width=83 style='mso-width-source:userset;mso-width-alt:2656;width:62pt'>\n"
				+ " <col width=94 style='mso-width-source:userset;mso-width-alt:3008;width:71pt'>\n"
				+ " <tr height=21 style='height:15.75pt'>\n"
				+ "  <td colspan=4 height=21 class=xl7015089 dir=LTR width=400 style='border-right:\n"
				+ "  .5pt solid black;height:15.75pt;width:300pt'>深资背景企业数量</td>\n"
				+ " </tr>\n"
				+ " <tr height=21 style='mso-height-source:userset;height:15.95pt'>\n"
				+ "  <td height=21 class=xl6415089 style='height:15.95pt;border-top:none'>项目</td>\n"
				+ "  <td height=21 class=xl6415089 style='height:15.95pt;border-top:none'>本月新增</td>\n"
				+ "  <td class=xl6515089 style='border-top:none;border-left:none'>同比增长</td>\n"
				+ "  <td class=xl6515089 style='border-top:none;border-left:none'>本月累计</td>\n"
				+ " </tr>");
		for (int i = 0, j = num.size(); i < j; i++) {
			sb.append("<tr height=21 style='mso-height-source:userset;height:15.95pt'>\n"
					+ "  <td height=21 class=xl6615089 style='height:15.95pt;border-top:none'>"
					+ num.get(i).get("项目")
					+ "</td>\n"
					+ "  <td class=xl6715089 align=right style='border-top:none;border-left:none'>"
					+ num.get(i).get("本月新增")
					+ "</td>\n"
					+ "  <td class=xl6715089 align=right style='border-top:none;border-left:none'>"
					+ num.get(i).get("同比增长")
					+ "</td>\n"
					+ "  <td class=xl6815089 align=right style='border-top:none;border-left:none'>"
					+ num.get(i).get("本月累计") + "</td>\n" + " </tr>");
			
		}
		sb.append("</table>\n" + "</div>\n" + "</body>\n" + "</html>");
		return sb.toString();
	}
}
