server:
  port: 10090
dubbo:
  application:
    name: yitao-seckill-web
    qos-enable: false
  registry:
    address: zookeeper://192.168.3.201:2181
spring:
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: common
  redis:
    host: 192.168.3.201
    password: redis-01